<script setup lang="ts">
import Heading from '@/components/Heading.vue';
import Pagination from '@/components/Pagination.vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AppLayout from '@/layouts/AppLayout.vue';
// Routes will be generated by Wayfinder
function create() {
    return { url: '/messages/create' };
}

function edit(args: { message: string }) {
    return { url: `/messages/${args.message}/edit` };
}
import type { BreadcrumbItem } from '@/types';
import { Head, Link, router } from '@inertiajs/vue3';
import { Edit, Mail, Plus, Trash2 } from 'lucide-vue-next';
import { computed, ref } from 'vue';

interface PaginationLink {
    url: string | null;
    label: string;
    active: boolean;
}

interface Paginated<T> {
    data: T[];
    links: PaginationLink[];
    current_page: number;
    last_page: number;
    per_page: number;
    total: number;
}

interface User {
    id: string;
    nome_completo: string;
}

interface Message {
    id: string;
    titulo: string;
    conteudo: string;
    lida: boolean;
    ativo: boolean;
    remetente: User | null;
    destinatario: User | null;
    is_sender: boolean;
    created_at: string;
    updated_at: string;
}

interface Props {
    messages: Paginated<Message>;
    filters: {
        search?: string | null;
        read?: string | null;
        active?: string | null;
    };
}

const props = defineProps<Props>();

const breadcrumbItems: BreadcrumbItem[] = [
    {
        title: 'Mensagens',
        href: '/messages',
    },
];

const search = ref(props.filters.search ?? '');
const read = ref(props.filters.read ?? '');
const active = ref(props.filters.active ?? '');

const hasAnyFilter = computed(() => !!search.value || read.value !== '' || active.value !== '');

function applyFilters() {
    router.get(
        '/messages',
        {
            search: search.value || undefined,
            read: read.value || undefined,
            active: active.value || undefined,
        },
        {
            preserveState: true,
            preserveScroll: true,
            replace: true,
        },
    );
}

function clearFilters() {
    search.value = '';
    read.value = '';
    active.value = '';
    applyFilters();
}

function formatDate(date: string): string {
    return new Date(date).toLocaleString('pt-BR', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
}

function deleteMessage(messageId: string) {
    if (confirm('Tem certeza que deseja excluir esta mensagem?')) {
        router.delete(`/messages/${messageId}`, {
            preserveScroll: true,
        });
    }
}
</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbItems">
        <Head title="Mensagens" />

        <div class="space-y-6">
            <div class="flex items-start justify-between gap-4">
                <div class="mt-2">
                    <Heading
                        title="Mensagens"
                        description="Gerencie suas mensagens"
                        :icon="Mail"
                    />
                </div>

                <div class="mt-2">
                    <Button as-child>
                        <Link :href="create()" class="flex items-center gap-2">
                            <Plus class="h-4 w-4" />
                            Nova mensagem
                        </Link>
                    </Button>
                </div>
            </div>

            <div class="rounded-xl border bg-card p-4 shadow-sm">
                <div
                    class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"
                >
                    <div class="flex flex-1 flex-col gap-3 sm:flex-row">
                        <div class="flex-1">
                            <Input
                                v-model="search"
                                placeholder="Buscar por título ou conteúdo..."
                                @keyup.enter="applyFilters"
                            />
                        </div>

                        <select
                            v-model="read"
                            class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm sm:w-44"
                            @change="applyFilters"
                        >
                            <option value="">Todas</option>
                            <option value="true">Lidas</option>
                            <option value="false">Não lidas</option>
                        </select>

                        <select
                            v-model="active"
                            class="h-10 w-full rounded-md border border-input bg-background px-3 text-sm sm:w-44"
                            @change="applyFilters"
                        >
                            <option value="">Todos status</option>
                            <option value="true">Ativas</option>
                            <option value="false">Inativas</option>
                        </select>
                    </div>

                    <div class="flex items-center gap-2">
                        <Button variant="secondary" @click="applyFilters">
                            Filtrar
                        </Button>
                        <Button
                            v-if="hasAnyFilter"
                            variant="ghost"
                            @click="clearFilters"
                        >
                            Limpar
                        </Button>
                    </div>
                </div>
            </div>

            <div class="rounded-xl border bg-card shadow-sm">
                <div class="overflow-x-auto">
                    <table class="w-full text-left text-sm">
                        <thead
                            class="border-b bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500 dark:bg-neutral-900/40 dark:text-neutral-400"
                        >
                            <tr>
                                <th class="px-4 py-3">Título</th>
                                <th class="px-4 py-3">Remetente</th>
                                <th class="px-4 py-3">Destinatário</th>
                                <th class="px-4 py-3">Status</th>
                                <th class="px-4 py-3">Data</th>
                                <th class="px-4 py-3 text-right">Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr
                                v-for="message in props.messages.data"
                                :key="message.id"
                                class="border-b last:border-0"
                            >
                                <td class="px-4 py-3">
                                    <div class="font-medium">{{ message.titulo }}</div>
                                    <div
                                        class="mt-0.5 line-clamp-1 text-xs text-muted-foreground"
                                    >
                                        {{ message.conteudo }}
                                    </div>
                                </td>
                                <td class="px-4 py-3">
                                    {{ message.remetente?.nome_completo ?? '—' }}
                                </td>
                                <td class="px-4 py-3">
                                    {{ message.destinatario?.nome_completo ?? '—' }}
                                </td>
                                <td class="px-4 py-3">
                                    <div class="flex flex-col gap-1">
                                        <Badge
                                            :variant="message.lida ? 'default' : 'secondary'"
                                        >
                                            {{ message.lida ? 'Lida' : 'Não lida' }}
                                        </Badge>
                                        <Badge
                                            :variant="message.ativo ? 'default' : 'destructive'"
                                        >
                                            {{ message.ativo ? 'Ativa' : 'Inativa' }}
                                        </Badge>
                                    </div>
                                </td>
                                <td class="px-4 py-3">
                                    <div class="text-xs text-muted-foreground">
                                        {{ formatDate(message.created_at) }}
                                    </div>
                                </td>
                                <td class="px-4 py-3">
                                    <div class="flex items-center justify-end gap-2">
                                        <Button
                                            v-if="message.is_sender"
                                            as-child
                                            size="sm"
                                            variant="ghost"
                                            class="hover:bg-transparent"
                                        >
                                            <Link :href="edit({ message: message.id })">
                                                <Edit
                                                    class="h-4 w-4 text-amber-500 dark:text-amber-400"
                                                />
                                            </Link>
                                        </Button>
                                        <Button
                                            size="sm"
                                            variant="ghost"
                                            class="hover:bg-transparent"
                                            @click="deleteMessage(message.id)"
                                        >
                                            <Trash2
                                                class="h-4 w-4 text-red-500 dark:text-red-400"
                                            />
                                        </Button>
                                    </div>
                                </td>
                            </tr>

                            <tr v-if="props.messages.data.length === 0">
                                <td
                                    colspan="6"
                                    class="px-4 py-10 text-center text-sm text-muted-foreground"
                                >
                                    Nenhuma mensagem encontrada.
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div
                    class="flex flex-col gap-3 border-t p-4 sm:flex-row sm:items-center sm:justify-between"
                >
                    <p class="text-sm text-muted-foreground">
                        Total: <span class="font-medium">{{ props.messages.total }}</span>
                    </p>
                    <Pagination :links="props.messages.links" />
                </div>
            </div>
        </div>
    </AppLayout>
</template>
