-- Schemas usados pelo Edully (multi-tenant / search_path)
CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS escola;
CREATE SCHEMA IF NOT EXISTS laravel;
CREATE SCHEMA IF NOT EXISTS saas;

GRANT ALL ON SCHEMA shared TO CURRENT_USER;
GRANT ALL ON SCHEMA escola TO CURRENT_USER;
GRANT ALL ON SCHEMA laravel TO CURRENT_USER;
GRANT ALL ON SCHEMA saas TO CURRENT_USER;
